# Generated by Django 3.0.8 on 2020-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('sexo', models.CharField(default='', max_length=10)),
                ('cargo', models.CharField(default='', max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
