# Generated by Django 3.0.8 on 2020-08-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('esterilizado', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('sintomas', models.CharField(max_length=200)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'adoptado'), ('E', 'en_adopcion'), ('C', 'colonia'), ('P', 'colonia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('ubicacion', models.CharField(default='', max_length=200)),
                ('contacto', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('sexo', models.CharField(default='', max_length=10)),
                ('cargo', models.CharField(choices=[('A', 'Admin'), ('V', 'Voluntario'), ('O', 'Organizador'), ('E', 'Externo')], max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=1)),
                ('long', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gpa.Recurso')),
                ('fechaCompra', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('active', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.EnfermedadAnimal')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.Medicina')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPonerAdopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Animal')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.Ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('costo', models.FloatField(default=1)),
                ('idOrganizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Organizacion')),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Recurso')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Persona'),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.EstadoAnimal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='historial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.HistorialMedico'),
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('idAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Animal')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Persona')),
            ],
        ),
    ]
