# Generated by Django 3.0.9 on 2020-09-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
