# Generated by Django 3.0.9 on 2020-08-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='esterilizado',
            new_name='esterelizado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='descripcion',
        ),
    ]
