# Generated by Django 3.0.9 on 2020-09-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioponeradopcion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Animal'),
        ),
        migrations.AlterField(
            model_name='formularioponeradopcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='gpa.Persona'),
        ),
    ]
