# Generated by Django 3.0.9 on 2020-08-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPonerAdopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('animal', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=20)),
            ],
        ),
    ]
