# Generated by Django 3.0.9 on 2020-08-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_auto_20200822_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dueno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.Persona'),
        ),
    ]
