# Generated by Django 3.0.9 on 2020-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0002_formularioponeradopcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('esterilizado', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
