# Generated by Django 3.0.9 on 2020-08-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dueno',
            field=models.ForeignKey(default='9999999999', on_delete=django.db.models.deletion.CASCADE, to='gpa.Usuario'),
        ),
        migrations.AlterField(
            model_name='formularioponeradopcion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa.Animal'),
        ),
    ]
