# Generated by Django 3.0.9 on 2020-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_auto_20200822_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='esterelizado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
