# Generated by Django 3.0.9 on 2020-08-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0004_auto_20200816_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('sintomas', models.CharField(max_length=200)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'adoptado'), ('E', 'en_adopcion'), ('C', 'colonia'), ('P', 'colonia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCompra', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='formularioponeradopcion',
            name='motivo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='formularioponeradopcion',
            name='user',
            field=models.ForeignKey(default='9999999999', on_delete=django.db.models.deletion.CASCADE, to='gpa.Usuario'),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.EnfermedadAnimal')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.Medicina')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.EstadoAnimal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='historial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpa.HistorialMedico'),
        ),
    ]
