# Generated by Django 3.0.9 on 2020-08-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0004_auto_20200822_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='esterelizado',
            field=models.CharField(max_length=3),
        ),
    ]
