# Generated by Django 3.0.9 on 2020-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0005_auto_20200822_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
