# Generated by Django 3.0.9 on 2020-08-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0006_auto_20200822_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(max_length=50),
        ),
    ]
