import { Animal } from './componentes/models/animal';

export const ANIMALS: Animal[] = [
    {
      nombre: 'Juanito',
      tipo: 'gato',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'gato',
      id: 1,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Amanda',
      tipo: 'gato',
      edad: 6,
      raza: 'mestizo',
      sexo: 'Hembra',
      picture: 'gato',
      id: 2,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Mota',
      tipo: 'perro',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 3,
      contacto :'0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Claudio',
      tipo: 'perro',
      edad: 2,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 4,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Ramses',
      tipo: 'gato',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'gato',
      id: 5,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Mechi',
      tipo: 'gato',
      edad: 6,
      raza: 'mestizo',
      sexo: 'Hembra',
      picture: 'gato',
      id: 6,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Menique',
      tipo: 'perro',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 7,
      contacto :'0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Jumbo',
      tipo: 'perro',
      edad: 2,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 8,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Juanito',
      tipo: 'gato',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'gato',
      id: 9,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Amanda',
      tipo: 'gato',
      edad: 6,
      raza: 'mestizo',
      sexo: 'Hembra',
      picture: 'gato',
      id: 10,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Mota',
      tipo: 'perro',
      edad: 1,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 11,
      contacto :'0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    },
    {
      nombre: 'Claudio',
      tipo: 'perro',
      edad: 2,
      raza: 'mestizo',
      sexo: 'Macho',
      picture: 'perro',
      id: 12,
      contacto : '0998871624',
      motivo : 'No tengo suficiente espacio en mi casa',
      images : [],
    }
  ];
